module.exports = {
  nihongoSidebar: [
    'nihongo',
    {
      type: 'category', 
      label: 'ไวยากรณ์ภาษาญี่ปุ่น', 
      collapsed: false, 
      items: ['grammar/index',
        {
          type: 'category',
          label: 'ไวยากรณ์ N1',
          collapsed: false,
          items: [
            'grammar/n1/index',
            'grammar/n1/ka-ina-ka',
            'grammar/n1/ka-no-gotoku',
            'grammar/n1/taritomo-nai',
            'grammar/n1/temae',
            'grammar/n1/to-omoikiya',
            'grammar/n1/towaie',
            'grammar/n1/nagara-no',
            'grammar/n1/ni-itaru-made',
            'grammar/n1/niwa-nari',
            'grammar/n1/meku',
            'grammar/n1/n-bakari-ni',
          ]
        },
        {
          type: 'category',
          label: 'ไวยากรณ์ N2',
          collapsed: false,
          items: [
            'grammar/n2/index',
            'grammar/n2/kai-ga-aru',
            'grammar/n2/kagiri-dewa',
            'grammar/n2/kaneru',
            'grammar/n2/kara-to-itte',
            'grammar/n2/ge',
            'grammar/n2/zaru-wo-enai',
            'grammar/n2/tsutsu',
            'grammar/n2/tsutsu-aru',
            'grammar/n2/ppoi',
            'grammar/n2/ni-kakawarazu',
            'grammar/n2/nominarazu',
            'grammar/n2/mono',
            'grammar/n2/yara-yara',
          ]
        },
        {
          type: 'category',
          label: 'ไวยากรณ์ N3',
          collapsed: false,
          items: [
            'grammar/n3/index',
            'grammar/n3/uchi-ni',
            'grammar/n3/okage-de',
            'grammar/n3/gachi',
            'grammar/n3/kara-koso',
            'grammar/n3/kuse-ni',
            'grammar/n3/saichuu-ni',
            'grammar/n3/zu-ni',
            'grammar/n3/sei-de',
            'grammar/n3/tamae',
            'grammar/n3/ppanashi',
            'grammar/n3/te-kara-wa',
            'grammar/n3/nado-nante',
            'grammar/n3/ni-oite',
            'grammar/n3/ni-kurabete',
            'grammar/n3/beki',
            'grammar/n3/wake-ni-wa-ikanai',
          ]
        },
      ],
    }
  ],
};
