module.exports = {
  nihongoSidebar: [
    'nihongo',
    {
      type: 'category', 
      label: 'ไวยากรณ์ภาษาญี่ปุ่น', 
      collapsed: false, 
      items: [
        {
          type: 'category',
          label: 'ไวยากรณ์ N1',
          collapsed: false,
          items: [{type: 'autogenerated', dirName: 'grammar/n1'}]
        },
        {
          type: 'category',
          label: 'ไวยากรณ์ N2',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'grammar/n2'}]
        },
        {
          type: 'category',
          label: 'ไวยากรณ์ N3',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'grammar/n3'}]
        },
      ],
    }
  ],
};
